FROM python:3-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
COPY requirements.txt ./
COPY config.py ./
COPY api.py ./
COPY encoder.py ./
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8080
CMD ["python", "api.py"]